feat: fix toast
Hug-For-Bug/music-app pull request #20
Opened 2023-02-26 14:48 UTC by ZulfanoRp

2023-02-26 18:07 UTC, KrishnaHendra commented on public/admin/js/dataUser.js
> +        toastrAlert("User Data Updated Successfully!", "Updated").then(
then e lek ditambah kyok ngene tetep berfungsi a? lek normal jos ok wisan

2023-02-26 18:07 UTC, KrishnaHendra commented on public/admin/js/dataUser.js
> +        $.ajax({
tambah ajax header

2023-02-26 18:07 UTC, KrishnaHendra commented on public/admin/js/dataUser.js
> +            contentType: false,
contentType hapus ae lek iki ga fungsi

2023-02-26 18:10 UTC, KrishnaHendra requested changes

2023-02-26 18:10 UTC, KrishnaHendra commented on public/admin/js/dataUser.js
> +    $("#form_create").submit(function (e) {
ambek iki lek id di generalno ae ojo nggawe undescore, nggawe camelCase ae formCreate

2023-02-26 18:55 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
> +        toastrAlert("User Data Updated Successfully!", "Updated").then(
fungsi kok, aman aman

2023-02-26 18:55 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
> +        $.ajax({
biar kenapa iku

2023-02-26 18:55 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
> +            contentType: false,
ok siap siap

2023-02-26 18:56 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
> +    $("#form_create").submit(function (e) {
oh oke oke siap

2023-02-27 03:42 UTC, KrishnaHendra commented on public/admin/js/dataUser.js
> +        $.ajax({
biasae lek js e wes akeh disaranno nggawe camelCase ae cek ga bingungi kedepan e

2023-02-27 03:44 UTC, KrishnaHendra requested changes

2023-02-27 03:44 UTC, KrishnaHendra commented on public/admin/js/dataUser.js
> +    const createStatus = localStorage.getItem("create-success");
iki edit mbek toastr e iku satu halaman a? opo bedo kyok register terus nge redirect nng login?,
lek ancen satu halaman kudue ga nggawe localStorage

2023-02-27 06:54 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
> +        $.ajax({
maksude ajak header e gae opo?

2023-02-27 08:06 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
> +    const createStatus = localStorage.getItem("create-success");
iyo satu halaman nak, ok tak coba e dulu

2023-03-07 09:24 UTC, merged