validation for user in section edit
Hug-For-Bug/music-app pull request #32
Opened 2023-04-03 04:35 UTC by ZulfanoRp

2023-04-03 18:21 UTC, KrishnaHendra requested changes
laine wes ok jos

2023-04-03 18:21 UTC, KrishnaHendra commented on public/admin/js/dataUser.js
>      $("#alertAdmin").hide(300);
interval show/hide e di sama ratano 500 ae kyok wong" biasae lek gak 1000 cek ngga auto show kyok bug

2023-04-04 09:21 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
> +let activeTab = localStorage.getItem("activeTab");
hmm okay

2023-04-04 09:21 UTC, ZulfanoRp commented on public/admin/js/dataUser.js
>      $("#alertAdmin").hide(300);
oh oke oke

2023-04-06 14:36 UTC, merged